//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.04.21 at 10:50:11 AM CEST 
//
package org.ecg.refdata.datasource.xml;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the org.ecg.refdata.datasource.xml package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: org.ecg.refdata.datasource.xml
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReferenceData.DocumentType }
     *
     */
    public ReferenceData.DocumentType createReferenceDataDocumentType() {
        return new ReferenceData.DocumentType();
    }

    /**
     * Create an instance of {@link ReferenceData.Correlation }
     *
     */
    public ReferenceData.Correlation createReferenceDataCorrelation() {
        return new ReferenceData.Correlation();
    }

    /**
     * Create an instance of {@link ReferenceData.ValueAdjustement.CodeDescription
     * }
     *
     */
    public ReferenceData.ValueAdjustement.CodeDescription createReferenceDataValueAdjustementCodeDescription() {
        return new ReferenceData.ValueAdjustement.CodeDescription();
    }

    /**
     * Create an instance of {@link ReferenceData.Country.CodeDescription }
     *
     */
    public ReferenceData.Country.CodeDescription createReferenceDataCountryCodeDescription() {
        return new ReferenceData.Country.CodeDescription();
    }

    /**
     * Create an instance of {@link ReferenceData.SimpleItem.CodeDescription }
     *
     */
    public ReferenceData.SimpleItem.CodeDescription createReferenceDataSimpleItemCodeDescription() {
        return new ReferenceData.SimpleItem.CodeDescription();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryHoliday }
     *
     */
    public ReferenceData.CountryHoliday createReferenceDataCountryHoliday() {
        return new ReferenceData.CountryHoliday();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeLSD
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeLSD createReferenceDataCustomsOfficeCustomsOfficeLSD() {
        return new ReferenceData.CustomsOffice.CustomsOfficeLSD();
    }

    /**
     * Create an instance of {@link ReferenceData.ValueAdjustement }
     *
     */
    public ReferenceData.ValueAdjustement createReferenceDataValueAdjustement() {
        return new ReferenceData.ValueAdjustement();
    }

    /**
     * Create an instance of {@link ReferenceData.Location }
     *
     */
    public ReferenceData.Location createReferenceDataLocation() {
        return new ReferenceData.Location();
    }

    /**
     * Create an instance of {@link ReferenceData.CommodityCode.CodeDescription
     * }
     *
     */
    public ReferenceData.CommodityCode.CodeDescription createReferenceDataCommodityCodeCodeDescription() {
        return new ReferenceData.CommodityCode.CodeDescription();
    }

    /**
     * Create an instance of {@link ReferenceData.CommodityCode }
     *
     */
    public ReferenceData.CommodityCode createReferenceDataCommodityCode() {
        return new ReferenceData.CommodityCode();
    }

    /**
     * Create an instance of {@link ReferenceData.SimpleItem }
     *
     */
    public ReferenceData.SimpleItem createReferenceDataSimpleItem() {
        return new ReferenceData.SimpleItem();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeDedicatedTrader
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeDedicatedTrader createReferenceDataCustomsOfficeCustomsOfficeDedicatedTrader() {
        return new ReferenceData.CustomsOffice.CustomsOfficeDedicatedTrader();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryRegion }
     *
     */
    public ReferenceData.CountryRegion createReferenceDataCountryRegion() {
        return new ReferenceData.CountryRegion();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine createReferenceDataCustomsOfficeCustomsOfficeTimetableCustomsOfficeTimetableLine() {
        return new ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryRegion.Holiday.HolidayLSD
     * }
     *
     */
    public ReferenceData.CountryRegion.Holiday.HolidayLSD createReferenceDataCountryRegionHolidayHolidayLSD() {
        return new ReferenceData.CountryRegion.Holiday.HolidayLSD();
    }

    /**
     * Create an instance of {@link ReferenceData.ValueAdjustement.Apportionment
     * }
     *
     */
    public ReferenceData.ValueAdjustement.Apportionment createReferenceDataValueAdjustementApportionment() {
        return new ReferenceData.ValueAdjustement.Apportionment();
    }

    /**
     * Create an instance of {@link ReferenceData }
     *
     */
    public ReferenceData createReferenceData() {
        return new ReferenceData();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeSpecificNotes
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeSpecificNotes createReferenceDataCustomsOfficeCustomsOfficeSpecificNotes() {
        return new ReferenceData.CustomsOffice.CustomsOfficeSpecificNotes();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryRegion.CountryRegionLSD
     * }
     *
     */
    public ReferenceData.CountryRegion.CountryRegionLSD createReferenceDataCountryRegionCountryRegionLSD() {
        return new ReferenceData.CountryRegion.CountryRegionLSD();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryUnavailability }
     *
     */
    public ReferenceData.CountryUnavailability createReferenceDataCountryUnavailability() {
        return new ReferenceData.CountryUnavailability();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeTimetable
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeTimetable createReferenceDataCustomsOfficeCustomsOfficeTimetable() {
        return new ReferenceData.CustomsOffice.CustomsOfficeTimetable();
    }

    /**
     * Create an instance of {@link ReferenceData.NameAndDescription }
     *
     */
    public ReferenceData.NameAndDescription createReferenceDataNameAndDescription() {
        return new ReferenceData.NameAndDescription();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryRegion.Holiday }
     *
     */
    public ReferenceData.CountryRegion.Holiday createReferenceDataCountryRegionHoliday() {
        return new ReferenceData.CountryRegion.Holiday();
    }

    /**
     * Create an instance of {@link ReferenceData.LocalClearanceAuthorization }
     *
     */
    public ReferenceData.LocalClearanceAuthorization createReferenceDataLocalClearanceAuthorization() {
        return new ReferenceData.LocalClearanceAuthorization();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryUnavailability.SystemUnavailability
     * }
     *
     */
    public ReferenceData.CountryUnavailability.SystemUnavailability createReferenceDataCountryUnavailabilitySystemUnavailability() {
        return new ReferenceData.CountryUnavailability.SystemUnavailability();
    }

    /**
     * Create an instance of {@link ReferenceData.UNLOCODE }
     *
     */
    public ReferenceData.UNLOCODE createReferenceDataUNLOCODE() {
        return new ReferenceData.UNLOCODE();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine.CustomsOfficeRoleTraffic
     * }
     *
     */
    public ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine.CustomsOfficeRoleTraffic createReferenceDataCustomsOfficeCustomsOfficeTimetableCustomsOfficeTimetableLineCustomsOfficeRoleTraffic() {
        return new ReferenceData.CustomsOffice.CustomsOfficeTimetable.CustomsOfficeTimetableLine.CustomsOfficeRoleTraffic();
    }

    /**
     * Create an instance of {@link ReferenceData.CustomsOffice }
     *
     */
    public ReferenceData.CustomsOffice createReferenceDataCustomsOffice() {
        return new ReferenceData.CustomsOffice();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryHoliday.Holiday.HolidayLSD
     * }
     *
     */
    public ReferenceData.CountryHoliday.Holiday.HolidayLSD createReferenceDataCountryHolidayHolidayHolidayLSD() {
        return new ReferenceData.CountryHoliday.Holiday.HolidayLSD();
    }

    /**
     * Create an instance of {@link ReferenceData.Country }
     *
     */
    public ReferenceData.Country createReferenceDataCountry() {
        return new ReferenceData.Country();
    }

    /**
     * Create an instance of {@link ReferenceData.ExchangeRate }
     *
     */
    public ReferenceData.ExchangeRate createReferenceDataExchangeRate() {
        return new ReferenceData.ExchangeRate();
    }

    /**
     * Create an instance of {@link ReferenceData.CountryHoliday.Holiday }
     *
     */
    public ReferenceData.CountryHoliday.Holiday createReferenceDataCountryHolidayHoliday() {
        return new ReferenceData.CountryHoliday.Holiday();
    }

    /**
     * Create an instance of {@link ReferenceData.DocumentType.CodeDescription }
     *
     */
    public ReferenceData.DocumentType.CodeDescription createReferenceDataDocumentTypeCodeDescription() {
        return new ReferenceData.DocumentType.CodeDescription();
    }

}
